[package]
name = "http-basic-lambda"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = { path = "../../lambda-http" }
lambda_runtime = { path = "../../lambda-runtime" }
tokio = { version = "1", features = ["macros"] }
