[package]
name = "rds-iam-rust-lambda"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_runtime = { path = "../../lambda-runtime" }
serde_json = "1.0.137"
aws-config = { version = "1.5.14", features = ["behavior-version-latest"] }
aws-credential-types = "1.2.1"
aws-sigv4 = "1.2.7"
url = "2.5.4"
tokio = { version = "1.43.0", features = ["full"] }
sqlx = { version = "0.8.3", features = ["tls-rustls", "postgres", "runtime-tokio"] }
