[package]
name = "rds-iam-rust-lambda"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_runtime = { path = "../../lambda-runtime" }
serde_json = "1.0.140"
aws-config = { version = "1.8.1", features = ["behavior-version-latest"] }
aws-credential-types = "1.2.3"
aws-sigv4 = "1.3.3"
url = "2.5.4"
tokio = { version = "1.46.1", features = ["full"] }
sqlx = { version = "0.8.6", features = ["tls-rustls", "postgres", "runtime-tokio"] }
