[package]
name = "consumer"
version = "0.1.0"
edition = "2021"

[dependencies]
#aws dependencies
aws-sdk-config = "1.57.0"
aws-sdk-sqs = "1.54.0"
aws_lambda_events = { version = "0.16.0", features = ["sqs"], default-features = false }

#lambda runtime
lambda_runtime = { path = "../../../lambda-runtime" }
tokio = { version = "1", features = ["macros"] }

#shared lib
pizza_lib = { path = "../pizza_lib" }
