[package]
name = "consumer"
version = "0.1.0"
edition = "2021"


[dependencies]
#tracing
tracing = "0.1.40"
tracing-subscriber = "0.3.17"

#aws dependencies
aws-sdk-config = "0.35.0"
aws-sdk-sqs = "0.35.0"
aws_lambda_events = { version = "0.11.1", features = ["sqs"], default-features = false }

#lambda runtime
lambda_runtime = "0.8.1"
tokio = { version = "1", features = ["macros"] }

#shared lib
pizza_lib = { path = "../pizza_lib" }
