[package]
name = "http-axum-diesel"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8"
diesel = "2.2.11"
diesel-async = { version = "0.6.1", features = ["postgres", "bb8"] }
lambda_http = { path = "../../lambda-http" }
serde = "1.0.219"
futures-util = "0.3.31"
rustls = "0.23.28"
rustls-native-certs = "0.8.1"
tokio = { version = "1.46.1", default-features = false, features = ["macros", "rt-multi-thread"] }
tokio-postgres = "0.7.13"
tokio-postgres-rustls = "0.13.0"
