[package]
name = "lambda-http-attributes"
version = "0.1.0"
authors = ["Doug Tangren"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0" }
syn = { version = "1.0", features = ["full"] }
quote = "1"
