[package]
name = "producer"
version = "0.1.0"
edition = "2021"

[package.metadata.lambda.deploy]
env = { "QUEUE_URL" = "https://changeMe" } 

[dependencies]
#aws dependencies
aws-config = "1.5.14"
aws-sdk-sqs = "1.54.0"

#lambda runtime
lambda_runtime = { path = "../../../lambda-runtime" }
serde_json = "1.0.137"
tokio = { version = "1", features = ["macros"] }

#shared lib
pizza_lib = { path = "../pizza_lib" }
