[package]
name = "basic-lambda"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_runtime = { path = "../../lambda-runtime" }
serde = "1.0.136"
tokio = { version = "1", features = ["macros"] }

[dev-dependencies]
tokio-test = "0.4.2"