[package]
name = "extension-custom-events"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda-extension = { path = "../../lambda-extension" }
serde = "1.0.136"
tokio = { version = "1", features = ["macros"] }
