[package]
name = "lambda-logs-firehose-extension"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda-extension = { path = "../../lambda-extension" }
tokio = { version = "1.43.0", features = ["full"] }
aws-config = "1.5.14"
aws-sdk-firehose = "1.60.0"
