[package]
name = "lambda-logs-firehose-extension"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda-extension = { path = "../../lambda-extension" }
tokio = { version = "1.46.1", features = ["full"] }
aws-config = { version = "1.8.1", features = ["behavior-version-latest"] }
aws-sdk-firehose = "1.82.0"
