[package]
name = "lambda-logs-firehose-extension"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda-extension = { path = "../../lambda-extension" }
tokio = { version = "1.17.0", features = ["full"] }
aws-config = "0.13.0"
aws-sdk-firehose = "0.13.0"
