[package]
name = "lambda_integration_tests"
version = "0.4.1"
edition = "2018"
description = "AWS Lambda Runtime integration tests"
license = "Apache-2.0"
repository = "https://github.com/awslabs/aws-lambda-rust-runtime"
categories = ["web-programming::http-server"]
keywords = ["AWS", "Lambda", "API"]
readme = "../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_http = { path = "../lambda-http", version = "0.4.1" }
lambda_runtime = { path = "../lambda-runtime", version = "0.4.1" }
lambda_extension = { path = "../lambda-extension", version = "0.1.0" }
log = "0.4"
serde = { version = "1", features = ["derive"] }
simple_logger = { version = "1.15", default-features = false }
tokio = { version = "1", features = ["full"] }