[package]
name = "extension-logs-basic"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda-extension = { path = "../../lambda-extension" }
tokio = { version = "1", features = ["macros", "rt"] }
