[package]
name = "http-cors"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = { path = "../../lambda-http" }
tokio = { version = "1", features = ["macros"] }
tower-http = { version = "0.6", features = ["cors"] }
