[package]
name = "http-dynamodb"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
serde_dynamo = { version = "4.2.14", features = ["aws-sdk-dynamodb+1"] }
lambda_http = { path = "../../lambda-http" }
aws-sdk-dynamodb = "1.82.0"
aws-config = { version = "1.8.1", features = ["behavior-version-latest"] }
tokio = { version = "1.46.1", features = ["macros"] }
