[package]
name = "http-dynamodb"
version = "0.1.0"
edition = "2021"

[dependencies]
simple-error = "0.3.0"
serde_json = "1.0.107"
serde = { version = "1.0.189", features = ["derive"] }
serde_dynamo = {version = "^4.2.7", features = ["aws-sdk-dynamodb+0_33"]}
lambda_http = { path = "../../lambda-http" }
aws-sdk-dynamodb = "0.33.0"
aws-config = "0.56.1"
tokio = { version = "1.33.0", features = ["macros"] }
