name: Closed Issue Message
on:
    issues:
       types: [closed]
jobs:
    auto_comment:
        runs-on: ubuntu-latest
        steps:
        - uses: aws-actions/closed-issue-message@v1
          with:
            # These inputs are both required
            repo-token: "${{ secrets.GITHUB_TOKEN }}"
            message: |
                     ### ⚠️COMMENT VISIBILITY WARNING⚠️ 
                     Comments on closed issues are hard for the maintainers of this repository to see. 
                     If you need more assistance, please open a new issue that references this one. 
                     If you wish to keep having a conversation with other community members under this issue feel free to do so.
