name: Formatting and Linting

on: [push, pull_request]

jobs:
  fmt:
    name: Cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Run fmt check
        id: cargoFmt
        shell: bash
        run: cargo +nightly fmt --all -- --check
  clippy:
    name: Cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run clippy check
        id: cargoClippy
        shell: bash
        run: cargo clippy --workspace --all-features -- -D warnings
      
      