[package]
name = "http-tower-trace"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = { path = "../../lambda-http" }
lambda_runtime = "0.5.1"
tokio = { version = "1", features = ["macros"] }
tower-http = { version = "0.5", features = ["trace"] }
